In [78]:
# import libraries and load iris dataset
import numpy as np
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()

In [103]:
# exploring a bit
print(iris.keys())
print("Iris feature names: ", iris.feature_names)
print("Iris target names: ", iris.target_names)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
Iris features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Iris targets:  ['setosa' 'versicolor' 'virginica']


In [104]:
# 1- Load "data" and "target" from the dataset, and display the first 10 records of each.
data = iris.data
target = iris.target
print(data[:10])
print(target[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]


In [114]:
# 2- Concatenate “data” and "target" into a new array. Show the first 5 records.
feature_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df = pd.DataFrame(data=data, columns=feature_names)
df['Iris name'] = target
df['Iris name'] = df['Iris name'].apply(lambda x: 'sentosa' if x == 0 else ('versicolor' if x == 1 else 'virginica'))
print(df[:5])

   sepal_length  sepal_width  petal_length  petal_width Iris name
0           5.1          3.5           1.4          0.2   sentosa
1           4.9          3.0           1.4          0.2   sentosa
2           4.7          3.2           1.3          0.2   sentosa
3           4.6          3.1           1.5          0.2   sentosa
4           5.0          3.6           1.4          0.2   sentosa


In [115]:
# 3- Calculate the mean and standard deviation of sepal length ("sepal length (cm)") 
# and petal length ("petal length (cm)"). Display results to two decimal places.
mean_sepal = round(df['sepal_length'].mean(),2)
print("Sepal length mean: ", mean_sepal)
standard_deviation_sepal = round(df['sepal_length'].std(), 2)
print("Sepal standard deviation: ", standard_deviation_sepal)

mean_sepal = round(df['petal_length'].mean(),2)
print("Petal length mean: ", mean_sepal)
standard_deviation_sepal = round(df['petal_length'].std(), 2)
print("Petal standard deviation: ", standard_deviation_sepal)

--> parei aqui: print(df.describe)

Sepal length mean:  5.84
Sepal standard deviation:  0.83
Petal length mean:  3.76
Petal standard deviation:  1.77
<bound method NDFrame.describe of      sepal_length  sepal_width  petal_length  petal_width  Iris name
0             5.1          3.5           1.4          0.2    sentosa
1             4.9          3.0           1.4          0.2    sentosa
2             4.7          3.2           1.3          0.2    sentosa
3             4.6          3.1           1.5          0.2    sentosa
4             5.0          3.6           1.4          0.2    sentosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [28]:
# 4- Select a random sample of 20 records from the dataset
random_20_records = df.sample(n=20)
print(random_20_records)

     sepal_length  sepal_width  petal_length  petal_width
79            5.7          2.6           3.5          1.0
72            6.3          2.5           4.9          1.5
5             5.4          3.9           1.7          0.4
12            4.8          3.0           1.4          0.1
139           6.9          3.1           5.4          2.1
82            5.8          2.7           3.9          1.2
140           6.7          3.1           5.6          2.4
51            6.4          3.2           4.5          1.5
116           6.5          3.0           5.5          1.8
147           6.5          3.0           5.2          2.0
11            4.8          3.4           1.6          0.2
73            6.1          2.8           4.7          1.2
80            5.5          2.4           3.8          1.1
0             5.1          3.5           1.4          0.2
8             4.4          2.9           1.4          0.2
43            5.0          3.5           1.6          0.6
81            

In [82]:
# 5- Create an array that displays: 
# The average of each characteristic by species; 
# The standard deviation of each characteristic by species.

mean_sepal_length = df['sepal_length'].mean().round(2) #5.84
mean_sepal_width = df['sepal_width'].mean().round(2) #3.06
mean_petal_length = df['petal_length'].mean().round(2) #3.76
mean_petal_width = df['petal_width'].mean().round(2) #1.2
mean = [mean_sepal_length, mean_sepal_width, mean_petal_length, mean_petal_width]

std_sepal_lenth = df['sepal_length'].std().round(2)
std_sepal_width = df['sepal_width'].std().round(2)
std_petal_lenth = df['petal_length'].std().round(2)
std_petal_width = df['petal_width'].std().round(2)
std = [std_sepal_lenth, std_sepal_width, std_petal_lenth, std_petal_width]

mean_and_std = pd.DataFrame(np.column_stack([mean, std]), index=features_names, columns=['Median', 'Standard'])
mean_and_std

Median  Standard
sepal_length    5.84      0.83
sepal_width     3.06      0.44
petal_length    3.76      1.77
petal_width     1.20      0.76

In [89]:
# 6 - Calculate the amount of samples per species and
# Find the species with the average maximum value of the "sepal length (cm)" variable
print(f"Total of sepal: {df['sepal_length'].shape[0]} \nTotal of petal: {df['petal_length'].shape[0]}")


Total of sepal: 150 
Total of petal: 150
