In [27]:
# Importing libraries and load iris dataset
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()

In [28]:
# Exploring a bit
print(iris.keys())
print("Iris feature names: ", iris.feature_names)
print("Iris target names: ", iris.target_names)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
Iris feature names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Iris target names:  ['setosa' 'versicolor' 'virginica']


In [29]:
# 1- Load "data" and "target" from the dataset, and display the first 10 records of each.
data = np.array(iris.data)
target_1D = np.array(iris.target) # eh um flat array, ou seja, uma linha somente, não existe colunas porque se tratar de uma dimensão
# print(target_1D.shape)
target = target_1D[:, np.newaxis] #transformo o array de 1D em 2D e agora passa a ter 150 linhas e 1 coluna
# print(target.shape)
print(data[:10])
print(target[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [30]:
# 2 - Concatenate “data” and "target" into a new array. Show the first 5 records.
matrix = np.concatenate((data, target), axis=1)
print(matrix[:5])

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


In [31]:
# 3 - Calculate the mean and standard deviation of sepal length ("sepal length (cm)") 
# and petal length ("petal length (cm)"). Display results to two decimal places.
mean_sepal = matrix[:,0].mean().round(2)
print("Sepal length mean: ", mean_sepal)
std_sepal = matrix[:,0].std().round(2)
print("Sepal length std: ", std_sepal)

mean_petal = matrix[:,2].mean().round(2)
print("Petal length mean: ", mean_petal)
std_petal = matrix[:,2].std().round(2)
print("Petal length std: ", std_petal)

Sepal length mean:  5.84
Sepal length std:  0.83
Petal length mean:  3.76
Petal length std:  1.76


In [32]:
# 4 - Select a random sample of 20 records from the dataset
random_indices = np.random.randint(0, 149, 20)
random_indices
matrix[random_indices]

array([[5.7, 2.5, 5. , 2. , 2. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [6.3, 2.7, 4.9, 1.8, 2. ],
       [7.6, 3. , 6.6, 2.1, 2. ],
       [6.7, 3.3, 5.7, 2.1, 2. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [6.2, 3.4, 5.4, 2.3, 2. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [5.6, 2.7, 4.2, 1.3, 1. ],
       [5.5, 2.4, 3.7, 1. , 1. ],
       [5.6, 2.8, 4.9, 2. , 2. ],
       [5. , 3.3, 1.4, 0.2, 0. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [5.7, 3.8, 1.7, 0.3, 0. ]])

In [33]:
# 5 - Create an array that displays: 
# The average of each characteristic by species; 
# The standard deviation of each characteristic by species.
# column 4: 0 sentosa, 1 virginica, 2 virginica
setosa = matrix[matrix[:, 4] == 0]
versicolor = matrix[matrix[:, 4] == 1]
virginica = matrix[matrix[:, 4] == 2]

# characteristics: ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
setosa_mean = np.array([setosa[:, 0].mean(), setosa[:, 1].mean(), setosa[:, 2].mean(), setosa[:, 3].mean()])
setosa_std = np.array([setosa[:, 0].std(), setosa[:, 1].std(), setosa[:, 2].std(), setosa[:, 3].std()])

versicolor_mean = np.array([versicolor[:, 0].mean(), versicolor[:, 1].mean(), versicolor[:, 2].mean(), versicolor[:, 3].mean()])
versicolor_std = np.array([versicolor[:, 0].std(), versicolor[:, 1].std(), versicolor[:, 2].std(), versicolor[:, 3].std()])

virginica_mean = np.array([virginica[:, 0].mean(), virginica[:, 1].mean(), virginica[:, 2].mean(), virginica[:, 3].mean()])
virginica_std = np.array([virginica[:, 0].std(), virginica[:, 1].std(), virginica[:, 2].std(), virginica[:, 3].std()])

print(f"The setosa mean: {setosa_mean}")
print(f"The setosa std: {setosa_std}")
print(f"The versicolor mean: {versicolor_mean}")
print(f"The versicolor std: {versicolor_std}")
print(f"The virginica mean: {virginica_mean}")
print(f"The virginica std: {virginica_std}")


The setosa mean: [5.006 3.428 1.462 0.246]
The setosa std: [0.34894699 0.37525458 0.17191859 0.10432641]
The versicolor mean: [5.936 2.77  4.26  1.326]
The versicolor std: [0.51098337 0.31064449 0.46518813 0.19576517]
The virginica mean: [6.588 2.974 5.552 2.026]
The virginica std: [0.62948868 0.31925538 0.54634787 0.27188968]


In [34]:
# 6 - Calculate the amount of samples per species and
# Find the species with the average maximum value of the "sepal length (cm)" variable
print(f"Amount of elements per specie: ")
print(f"Setosa: {setosa.shape[0]}")
print(f"Versicolor: {versicolor.shape[0]}")
print(f"Virginica: {virginica.shape[0]}")
print(f"The specie with the average maximum value of the sepal length (cm): {virginica[:, 0].mean()} cm")

Amount of elements per specie: 
Setosa: 50
Versicolor: 50
Virginica: 50
The specie with the average maximum value of the sepal length (cm): 6.587999999999998 cm


In [39]:
# 7 - Calculate the correlation matrix between the variables
# Filter values greater than the avarage petal length and display it
# Filter the specie with the largest petals
data = matrix[:,0:4]
print(f"The correlation Matrix:\n{np.corrcoef(data.T)}")

petal_length_greater_mean = matrix[:,2] > mean_petal
print(f"values greater than the avarage petal length:\n{matrix[petal_length_greater_mean]}")

largest_petal = data[:, 2].max()
print(f"The specie with the largest petals is Virginica as it can see:\n{matrix[matrix[:,2] == largest_petal]}")


The correlation Matrix:
[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
values greater than the avarage petal length:
[[7.  3.2 4.7 1.4 1. ]
 [6.4 3.2 4.5 1.5 1. ]
 [6.9 3.1 4.9 1.5 1. ]
 [5.5 2.3 4.  1.3 1. ]
 [6.5 2.8 4.6 1.5 1. ]
 [5.7 2.8 4.5 1.3 1. ]
 [6.3 3.3 4.7 1.6 1. ]
 [6.6 2.9 4.6 1.3 1. ]
 [5.2 2.7 3.9 1.4 1. ]
 [5.9 3.  4.2 1.5 1. ]
 [6.  2.2 4.  1.  1. ]
 [6.1 2.9 4.7 1.4 1. ]
 [6.7 3.1 4.4 1.4 1. ]
 [5.6 3.  4.5 1.5 1. ]
 [5.8 2.7 4.1 1.  1. ]
 [6.2 2.2 4.5 1.5 1. ]
 [5.6 2.5 3.9 1.1 1. ]
 [5.9 3.2 4.8 1.8 1. ]
 [6.1 2.8 4.  1.3 1. ]
 [6.3 2.5 4.9 1.5 1. ]
 [6.1 2.8 4.7 1.2 1. ]
 [6.4 2.9 4.3 1.3 1. ]
 [6.6 3.  4.4 1.4 1. ]
 [6.8 2.8 4.8 1.4 1. ]
 [6.7 3.  5.  1.7 1. ]
 [6.  2.9 4.5 1.5 1. ]
 [5.5 2.4 3.8 1.1 1. ]
 [5.8 2.7 3.9 1.2 1. ]
 [6.  2.7 5.1 1.6 1. ]
 [5.4 3.  4.5 1.5 1. ]
 [6.  3.4 4.5 1.6 1. ]
 [6.7 3.1 4.

In [61]:
# 8 - Find the species with the largest difference between the avarage length of sepals and petals
# 0 sentosa, 1 virginica, 2 virginica
# ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
setosa_sepal_mean = matrix[matrix[:,4] == 0][:,0].mean()
setosa_petal_mean = matrix[matrix[:,4] == 0][:,2].mean()
virginica_sepal_mean = virginica_mean[0]
virignica_petal_mean = virginica_mean[2]
versicolor_sepal_mean = versicolor_mean[0]
versicolor_petal_mean = versicolor_mean[2]
differences = [np.abs(setosa_petal_mean - setosa_sepal_mean), 
               np.abs(virignica_petal_mean - virginica_sepal_mean), np.abs(versicolor_petal_mean - versicolor_sepal_mean)]
print(f"The absolute differences between petal and sepal are: {differences}\n" 
      f"and the specie with largest difference is the setosa as we can see: np.argmax(differences): {np.argmax(differences)}")

The absolute differences between petal and sepal are: [3.544, 1.0359999999999978, 1.6760000000000002]
 and the specie with largest difference is the setosa as we can see: np.argmax(differences): 0
