In [2]:
# import libraries and load iris dataset
import numpy as np
import pandas as pd
from sklearn import datasets
iris = datasets.load_iris()

In [3]:
# exploring a bit
print(iris.keys())
print("Iris feature names: ", iris.feature_names)
print("Iris target names: ", iris.target_names)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
Iris feature names:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Iris target names:  ['setosa' 'versicolor' 'virginica']


In [4]:
# 1- Load "data" and "target" from the dataset, and display the first 10 records of each.
data = iris.data
target = iris.target
print(data[:10])
print(target[:10])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]


In [5]:
# 2- Concatenate “data” and "target" into a new array. Show the first 5 records.
feature_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df = pd.DataFrame(data=data, columns=feature_names)
df['Iris name'] = target
df['Iris name'] = df['Iris name'].apply(lambda x: 'sentosa' if x == 0 else ('versicolor' if x == 1 else 'virginica'))
print(df[:5])

   sepal_length  sepal_width  petal_length  petal_width Iris name
0           5.1          3.5           1.4          0.2   sentosa
1           4.9          3.0           1.4          0.2   sentosa
2           4.7          3.2           1.3          0.2   sentosa
3           4.6          3.1           1.5          0.2   sentosa
4           5.0          3.6           1.4          0.2   sentosa


In [7]:
# 3- Calculate the mean and standard deviation of sepal length ("sepal length (cm)") 
# and petal length ("petal length (cm)"). Display results to two decimal places.
mean_sepal = round(df['sepal_length'].mean(),2)
print("Sepal length mean: ", mean_sepal)
standard_deviation_sepal = round(df['sepal_length'].std(), 2)
print("Sepal standard deviation: ", standard_deviation_sepal)

mean_sepal = round(df['petal_length'].mean(),2)
print("Petal length mean: ", mean_sepal)
standard_deviation_sepal = round(df['petal_length'].std(), 2)
print("Petal standard deviation: ", standard_deviation_sepal)

print("Checking the values:\n", df.describe())

Sepal length mean:  5.84
Sepal standard deviation:  0.83
Petal length mean:  3.76
Petal standard deviation:  1.77
Checking the values:
        sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [8]:
# 4- Select a random sample of 20 records from the dataset
random_20_records = df.sample(n=20)
print(random_20_records)

     sepal_length  sepal_width  petal_length  petal_width   Iris name
16            5.4          3.9           1.3          0.4     sentosa
61            5.9          3.0           4.2          1.5  versicolor
125           7.2          3.2           6.0          1.8   virginica
19            5.1          3.8           1.5          0.3     sentosa
42            4.4          3.2           1.3          0.2     sentosa
24            4.8          3.4           1.9          0.2     sentosa
144           6.7          3.3           5.7          2.5   virginica
32            5.2          4.1           1.5          0.1     sentosa
122           7.7          2.8           6.7          2.0   virginica
39            5.1          3.4           1.5          0.2     sentosa
2             4.7          3.2           1.3          0.2     sentosa
79            5.7          2.6           3.5          1.0  versicolor
64            5.6          2.9           3.6          1.3  versicolor
6             4.6   

In [37]:
# 5- Create an array that displays: 
# The average of each characteristic by species; 
# The standard deviation of each characteristic by species.
print(df.groupby(['Iris name']).mean())
print(df.groupby(['Iris name']).std())

            sepal_length  sepal_width  petal_length  petal_width
Iris name                                                       
sentosa            5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026
            sepal_length  sepal_width  petal_length  petal_width
Iris name                                                       
sentosa         0.352490     0.379064      0.173664     0.105386
versicolor      0.516171     0.313798      0.469911     0.197753
virginica       0.635880     0.322497      0.551895     0.274650


In [72]:
# 6- Calculate the amount of samples per species and
# Find the species with the average maximum value of the "sepal length (cm)" variable
print(df.groupby(['Iris name']).size())

print("The specie with the average maximum value of the sepal length (cm): ", 
      df.groupby(['Iris name']).mean()['sepal_length'].idxmax(), 
      df.groupby(['Iris name']).mean()['sepal_length'].max(), "cm")

Iris name
sentosa       50
versicolor    50
virginica     50
dtype: int64
The specie with the average maximum value of the sepal length (cm):  virginica 6.587999999999999 cm


In [125]:
# 7- Calculate the correlation matrix between the variables; 
# Filter values greater than the average petal length and display it; 
# Find the specimen with the largest petals.
df.groupby(['Iris name']).corr()



# print(f"The specimen with the largest petals:\n{df[['petal_length', 'Iris name']].max()}")


The specimen with the largest petals:
petal_length          6.9
Iris name       virginica
dtype: object


petal_length          6.9
Iris name       virginica
dtype: object